name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # replace `<your-repo>` with your Docker Hub repo name
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/bradbaze/hamalert-discord:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/bradbaze/hamalert-discord:${{ github.sha }}
